project:
  type: website
  output-dir: docs

website:
  title: "PA 446 Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: methods.qmd
        text: Data & Methods
      - href: analysis.qmd
        text: Analysis
      - href: findings.qmd
        text: Findings
    right:
      - icon: github
        href: https://github.com/kvent-stack/Final-Exam

format:
  html:
    theme: lux
    toc: true
    number-sections: true